server:
  #  servlet:
  #    context-path: /upload
  port: 9001

# 服务与数据库配置
spring:
  application:
    name: media-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_minio?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: admin123


## minio配置
minio:
  endpoint: http://192.168.31.32:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket:
    files: mediafiles
    video: videofiles

